theme = "speckleworks"
baseurl = "https://speckle.works"
title = "Speckle: Open Data Rich Design"
languageCode = "en-us"
SectionPagesMenu = "main"
pluralizelisttitles= "false"
pygmentsUseClassic=true

[menu]
  [[menu.main]]
      name = "Home"
      # pre = "&nbsp<img src='/img/2xlogo@4x.png' width='25'/>"
      # pre = "&nbsp<i class='fa fa-home'></i>"
      weight = 1
      identifier = "Speckle"
      url = "/"
  [[menu.main]]
    identifier = "log"
    name = "Log"
    title = "news"
    url = "/log/"
    weight = 20
  [[menu.main]]
      name = "Github"
      pre = "<i class='fa fa-github'></i>"
      weight = 30000
      url = "https://github.com/speckleworks"
  [[menu.main]]
      name = "Forum"
      pre = "<i class='fa fa-comments-o'></i>"
      weight = 35000
      url = "https://discourse.speckle.works/"


[params]
mainBlurb = "Open Design Collaboration"
secondaryBlurb = """
We reimagine the design process from the Internet up: Speckle is an open source (MIT) initiative for developing an extensible Design & AEC data <span class='emp'>communication and collaboration platform.</span>
"""
horizon2020 = "This project has received funding from the European Union’s Horizon 2020 research and innovation program under the Marie Sklodowska-Curie grant agreement No 642877."
# [params.features]
[[params.features]]
    name = "Interop Done Right"
    blurb = "Speckle's software agnostic and plays well with all major AEC software."
[[params.features]]
    name = "Fully Open Source"
    blurb = "The whole Speckle ecosystem is licensed under the MIT license, 100% Free. Forever."
[[params.features]]
    name = "Your Data: Your Ownership"
    blurb = "Deploy Speckle in-house or on the cloud: your choice. Your data stays yours."
[[params.features]]
    name = "Schema Agnostic"
    blurb = "IFC or in-house data models? No problems. Speckle handles everything you got."

